# Generated by Django 4.1.7 on 2023-04-05 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Freight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.BigIntegerField()),
                ('reception_date', models.DateField(null=True)),
                ('application_date', models.DateField()),
                ('price_without_taxes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FreightCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=11, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('method', models.CharField(choices=[('TRF', 'Transferencia'), ('CRD', 'Tarjeta'), ('CSH', 'Efectivo')], max_length=3)),
                ('paid_by', models.CharField(choices=[('C53', 'Chocolates 53 Sur'), ('ALE', 'Alejandra'), ('LOR', 'Lorena')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('measurement', models.CharField(choices=[('kg', 'kilogramos'), ('un', 'unidades')], default='kg', max_length=2)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product', to='warehouse.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=11, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.BigIntegerField(null=True)),
                ('date', models.DateField()),
                ('seller_name', models.CharField(blank=True, max_length=50, null=True)),
                ('freight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='warehouse.freight')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='warehouse.payment')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='warehouse.provider')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boxes_quantity', models.IntegerField()),
                ('amount_per_box', models.IntegerField()),
                ('price_per_box', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_item', to='warehouse.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='warehouse.purchase')),
            ],
        ),
        migrations.AddField(
            model_name='freight',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='warehouse.freightcompany'),
        ),
        migrations.AddField(
            model_name='freight',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freight_payment', to='warehouse.payment'),
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('price', models.IntegerField()),
                ('expiration_date', models.DateField(null=True)),
                ('shelf', models.CharField(choices=[('E1', 'Estante 1'), ('E2', 'Estante 2'), ('E3', 'Estante 3'), ('E4', 'Estante 4'), ('LP', 'Lateral Puerta')], max_length=3, null=True)),
                ('id_warehouse', models.IntegerField(null=True)),
                ('in_warehouse', models.BooleanField(default=True, null=True)),
                ('withdrawal_date', models.DateField(default=None, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='warehouse.product')),
                ('purchase_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='warehouse.purchaseitem')),
            ],
            options={
                'ordering': ['-in_warehouse', 'expiration_date'],
            },
        ),
        migrations.AddIndex(
            model_name='box',
            index=models.Index(fields=['in_warehouse', 'id'], name='warehouse_b_in_ware_5595f1_idx'),
        ),
    ]
